FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:build

RUN install_packages curl

RUN pip3 install OctoPrint==1.6.1

RUN PYTHONUSERBASE=/usr/local/ pip install --no-cache-dir \
    "https://github.com/kantlivelong/OctoPrint-PSUControl/archive/master.zip" \ 
    "https://github.com/marian42/octoprint-preheat/archive/master.zip" \
    "https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/releases/latest/download/master.zip" \
    "https://github.com/malnvenshorn/OctoPrint-FilamentManager/archive/master.zip" \
    "https://github.com/eyal0/OctoPrint-PrintTimeGenius/archive/master.zip"

# Seed the initial config.yaml
COPY ./config.yaml /data/config.yaml

WORKDIR /usr/src/app 
COPY start.sh start.sh

CMD ["sh","start.sh"]